### ISSUE TITLE
Update gateway /kafka/:topic endpoint to validate scopes

### ISSUE THREAD

**Issue by blabadi** [icgc-argo/platform-api#346]
Right now anyone/any application with valid ego token can use that endpoint to create kafka messages in the platform kafka cluster, we can and should enforce better authorization using token scopes (policy per topic maybe) to specify what can write to which topics

## Detailed Description

example
kship rdpc right now can get a token and write messages to song_analysis, but if by mistake or another thing, it can write to any other topic.

the token is open ended and the gateway right now just validates that the token is valid one from ego, which is not ideal

## Possible Implementation

use ego token scopes to specify what jwts allow callers to the /kafka/:topic endpoint to access which topics

**Comment by joneubank** [comment]
Some thoughts on what a scheme for this might look like:

1. Require all requests have a specific scope (ex. XYZ.WRITE) that would allow them to write to any topic - Really broad access to any agent we give permission to. Not a concern when all external publishers are controlled by the DCC, but this strategy needs to expand out to RDPCs that are outside of our control. I don't think this is secure enough
2. Policies that include the allowed topic names (ex. XYZ-score_analyses.WRITE) - Restricts access to any agent given that permission, allows DCC to control where external messages go so that external agents can't put messages on important internal topics.
3. Remove the kafka/topic endpoint in favour of specific endpoints for external agents to interact with, and write handlers for these endpoints that generate the messages for kafka and submit them. This is the most secure but at the cost of flexibility and developer overhead. There would still need to be scoped authorization rules for these endpoints which may or may not require new policies.

Considering these competing ideas I favour a system like #2 , which allows us to continue to use the system currently in place, that can expand to new use cases without development overhead (only requires ego policy additions), and keeps the control of what messages can go onto what topic go within the DCC developers/admin.

**Comment by joneubank** [comment]
I will use `DCCKAFKA-topic_name` as the pattern for a scope. The prefix `DCCKAFKA-` will be a configurable variable in the `program-api`
