### ISSUE TITLE
[API] Downloadable tsvs

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/platform-api#544]
- [ ] Extend API for be able to Download all the clinical data in the same tsv format as what they submitted
- [ ] Can also download tsv by individual file type
- [ ] Modify to include the filtered ids (i.e. downloads would be for what donors are loaded in UI)

Related Data hookup ticket:
https://github.com/icgc-argo/platform-ui/issues/2271

![image](https://user-images.githubusercontent.com/18424138/159768522-fba792e6-06c1-4b66-b6c9-65c2d7f4177c.png)

**Comment by lindaxiang** [comment]
Test API endpoint: https://clinical.qa.argo.cancercollaboratory.org/api-docs/#/Clinical%20Data/get_clinical_program__programId__clinical_tsv
- works for entityTypes of donor, treatment, chemotherapy,radiation,immunotherapy,surgery,exposure,biomarker,comorbidity
- do NOT work for other entityTypes: sample_registration, specimen, primary_diagnosis, hormone_therapy, follow_up, family_history

**Comment by edsu7** [comment]
Same findings as Linda.

Except `specimens` works instead of `specimen`.

Entity return + single donor filtering works, but multiple donor filtering does not.

Example of 

|Query|Curl Cmd|Functional|Additional info|
|--|--|--|--|
|Single donor|https://clinical.qa.argo.cancercollaboratory.org/clinical/program/DATA-CA/clinical-tsv?entityTypes=donor&donorIds=262723&completionState=all|Yes||
|Multiple donor|https://clinical.qa.argo.cancercollaboratory.org/clinical/program/DATA-CA/clinical-tsv?entityTypes=donor&donorIds=262723&donorIds=262725&completionState=all|No| Error 500 ```{"error": "TypeError","message": "donorIds.match is not a function"}```|
|Corrected multiple donor|https://clinical.qa.argo.cancercollaboratory.org/clinical/program/DATA-CA/clinical-tsv?entityTypes=donor&donorIds=262723\|\|donorIds=262725&completionState=all|Yes||

**Comment by b-f-chan** [comment]
Assign back to @demariadaniel for fixes per above findings

**Comment by lindaxiang** [comment]
@demariadaniel I tested from UI, and the following functions are working properly:
1. Download all the clinical data in the same tsv format as what they submitted
2. Can also download tsv by individual file type
3. The quick filter works and downloads would be for what donors are loaded in UI

Comments:
1. download files(for all the clinical and each individual file type) are all named the same for example: `HNAHAL-CA_Clinical_Data_20221010.zip`, it would be better to name them differently with file type. e.g., `HNAHAL-CA_Donor_20221010.zip`, `HNAHAL-CA_Sample_Registration_20221010.zip` and etc.

**Comment by Buwujiu** [comment]
Tested in QA, moving to awaiting release.
