### ISSUE TITLE
Audit Critical, High, Deprecated Security Alerts

### ISSUE THREAD

**Issue by Buwujiu** [icgc-argo/platform-api#550]
We need to address the critical, high, and/or deprecated security alerts: 
https://github.com/icgc-argo/platform-api/security/dependabot?page=1&q=is%3Aopen

**Scope of Ticket:**

- [ ] Run NPM audit to determine critical, high, deprecated alerts for `platform-api`
- [ ] Use audit results to prioritize & create separate tasks to handle the issues

**Comment by ciaranschutte** [comment]
some work started, minor version upgrades applied: https://github.com/icgc-argo/platform-api/pull/563

These are all major patches and come with breaking changes.
Using migration effort of 'Small', 'Medium' or 'Large' to denote effort.

#### Migration effort: Medium
Sam is working on very similar tickets, basing off her expertise.
Seems to mostly just be typings but it's for the large data sections so may be tricky.

| package | version migration |
| --- | --- |
| apollo-server-express | 2.25.4  =>  3.8.2    |
| graphql | 14.7.0  =>  16.5.0  |
| graphql-tools | 4.0.8  =>  8.2.12 |

#### Migration effort: Small
migration may be more involved (due to them being larger, non utility libraries) but breaking changes and our usage appear to be minimal

| package | version migration |
| --- | --- |
| @elastic/elasticsearch [^1] |  7.17.0  =>  8.2.1 | 
| http-proxy-middleware [^2] | 1.3.1   =>  2.0.6    |

#### Migration effort: Small
pretty light or utility libraries

| package | version migration |
| --- | --- |
| ts-interface-checker   |  0.2.1   =>  1.0.2    | 
| node-fetch [^3]   | 2.6.7   =>  3.2.5     |
| url-join | 4.0.1   =>  5.0.0 | 
| dataloader |1.4.0   =>  2.1.0 
|dotenv|8.6.0   =>  16.0.1| 
|filesize|6.4.0   =>  9.0.1|
|form-data|2.5.1   =>  4.0.0|





[^1]: https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/changelog-client.html
[^2]: https://github.com/chimurai/http-proxy-middleware/releases
[^3]: https://github.com/node-fetch/node-fetch/blob/HEAD/docs/v3-UPGRADE-GUIDE.md

**Comment by ciaranschutte** [comment]
@b-f-chan yeah "migration" may be poor phrasing on my part.
I can create tickets out of these findings. Is that your preferred output for this ticket?
Basically a ticket to actually do the upgrades not just see how involved they are

**Comment by b-f-chan** [comment]
After discussing with @ciaranschutte, he has already done much of the work in the sub-tasks here, so we will simply complete all tasks in this ticket to wrap it up for end of June 30 to July 14 sprint, instead of delegating further.

**Comment by b-f-chan** [comment]
2 other upgrade tasks need to be done separately from this scope

- (1) Node fetch & URL join
- (2) GraphQL --> Arranger has hard dependency on current GraphQL which needs Arranger upgrade as well so it's a bigger task

**Comment by b-f-chan** [comment]
For scope of this ticket, just the remaining testing needs to be fixed

**Comment by b-f-chan** [comment]
Target next week Monday (July 18th) to check-in on QA readinesss

**Comment by Buwujiu** [comment]
Remove useless tests that do not need node-fetch and url-join, if this helps to speed things up.

**Comment by ciaranschutte** [comment]
tests are working.
